---
- name: Flask Health Check Remediation
  hosts: all
  sources:
    - name: Listen for AlertManager webhooks
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Match any event
      condition: event is defined
      action:
        run_workflow_template:
          name: "Remediate Flask Service"
          organization: "Default"